on: [push, pull_request]

jobs:
  test-first-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11.0
        - macos-10.15
    steps:
    - uses: actions/checkout@v2
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v2
      with:
        path: build/bin
        key: neomura-setup-aseprite-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ matrix.os }}-${{ steps.prepare.outputs.sha }}
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
  test-subsequent-run:
    needs: test-first-run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11.0
        - macos-10.15
    steps:
    - uses: actions/checkout@v2
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v2
      with:
        path: build/bin
        key: neomura-setup-aseprite-cli-action-${{ GITHUB.REPOSITORY }}-${{ GITHUB.REF }}-${{ matrix.os }}-${{ steps.prepare.outputs.sha }}
    - uses: ilammy/msvc-dev-cmd@v1
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
